version: 2
jobs:
  build:
    docker:
      - image: node:7.8.0
    working_directory: ~/reactbkk-2.0.0
    steps:
      - checkout
      - add_ssh_keys
      - run: |
          npm install
      - run: |
          npm run build
      - run: |
          [ "${CIRCLE_BRANCH}" == "master" ] && git config --global user.name "CircleCI" && git config --global user.email "circleci@spacet.me" && npm run deploy
